name: Build project

on: [push]

jobs:
  testAllModes:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: path/to/your/project
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts